version: '3'

services:
  web:
    image: vivekdurai/funnel
    container_name: web
    ports:
      - 3000:3000
    command: sh ./runserver.staging.sh
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - postgres
      - redis
    extra_hosts:
      - "hasgeek.dev:127.0.0.1"
    volumes:
      - .:/app
      - $HOME/.aws/credentials:/app/.aws/credentials:ro
  redis:
    image: redis
  nginx:
    build:
      context: ./etc/nginx-staging
    container_name: nginx
    volumes:
      - static_data:/vol/static
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;error_log /dev/stdout info;\"'"
    depends_on:
      - web
  postgres:
    container_name: 'postgres'
    restart: always
    image: 'postgres:13'
    user: postgres
    ports:
      - 5432:5432
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
        PGUSER: postgres   
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
volumes:
  pgdata:
  static_data: