name: Coverage check

on:
  pull_request:
    branches: [master]

jobs:
  coverage-job:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: funnel_testing
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/hasgeek/flask-babelhg.git
          pip install -r test_requirements.txt
          pip install -r requirements.txt
      - name: Make JS
        run: make
      - name: Run tests
        run: ./runtests.sh
        env:
          SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@localhost/funnel_testing
