name: 'Staging workflow'
on:
  pull_request:
    branches:
      - master
env:
  VENV_BIN_PATH: /var/www/hasgeek/venv/bin
  PROJECT_PATH: /var/www/hasgeek/funnel-master
  BASEFRAME_BRANCH: master
jobs:
  deploy-staging:
    runs-on: self-hosted
    steps:
      - run: echo "branch - ${{ github.head_ref }}, ${{ github.ref }}"
      - run: echo $GITHUB_WORKSPACE
      - run: cd ${{ env.PROJECT_PATH }}; git checkout ${{ github.ref }}; git pull origin ${{ github.ref }}
      - run: ${{ env.sVENV_BIN_PATH }}/pip uninstall -y baseframe
      - run: ${{ env.sVENV_BIN_PATH }}/pip install git+https://github.com/hasgeek/baseframe.git@${{ env.BASEFRAME_BRANCH }}#egg=baseframe
      - run: cd ${{ env.PROJECT_PATH }}; make
      - run: sudo systemctl restart hasgeek
