name: 'Staging workflow'
on:
  push:
    branches:
      # update this to the branch of funnel that needs to be staged
      - gh-actions-staging
env:
  PROJECT_PATH: /var/www/funnel/staging
  # update this branch the branch of baseframe that needs to be staged
  BASEFRAME_BRANCH: master
jobs:
  deploy-staging:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - run: cd ${{ env.PROJECT_PATH }}; ./deploy.sh ${{ steps.vars.outputs.short_ref }} ${{ env.BASEFRAME_BRANCH }}
