name: 'Staging workflow'
on:
  pull_request:
    branches:
      - master
env:
  PROJECT_PATH: /var/www/hasgeek/funnel-master
  BASEFRAME_BRANCH: master
jobs:
  deploy-staging:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo $GITHUB_WORKSPACE
